import { Inter as FontSans } from 'next/font/google';

import { ReactQueryProvider } from '@/providers/reactQueryProvider';
import { dir } from 'i18next';

import { Lng } from '@/api/global.model';
import { languages } from '@/i18n/settings';
import MainLayout from '@/layouts/MainLayout';

import { cn } from '../../lib/utils';
import '../../styles/globals.css';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export const generateStaticParams = async () => {
  return languages.map((lng) => ({ lng }));
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    lng: Lng;
  };
};

const RootLayout = ({ children, params: { lng } }: RootLayoutProps) => {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={cn('bg-background font-sans antialiased', fontSans.variable)}>
        <ReactQueryProvider>
          <MainLayout lng={lng}>{children}</MainLayout>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
